image:
  file: .gitpod.dockerfile
ports:
  - port: 1080
    onOpen: notify
  - port: 1081
    onOpen: notify
  - port: 6080
    onOpen: notify
    onOpen: notify
  - port: 8080
    onOpen: notify
checkoutLocation: "go/src/github.com/xuiv/gost-heroku"
workspaceLocation: "go/src/github.com/xuiv/gost-heroku"
tasks:
  - init: >
      go get -v ./... &&
      go build -o app
    command: >
      ./app -L socks+ws://:8080 >/dev/null 2>&1 &
github:
    prebuilds:
        pullRequestsFromForks: true
