image:
  file: .gitpod.dockerfile
ports:
  - port: 1080
    onOpen: notify
  - port: 1081
    onOpen: notify
  - port: 1082
    onOpen: ignore    
  - port: 6080
    onOpen: open-browser
  - port: 8080
    onOpen: ignore
  - port: 8088
    onOpen: ignore    
checkoutLocation: "go/src/github.com/xuiv/gost-heroku"
workspaceLocation: "go/src/github.com/xuiv/gost-heroku"
tasks:
  - init: >
      export GO111MODULE=off && go get -v ./... &&
      go build -o app
    command: >
      python ad.py &
      ./app -L socks+ws://:1082 >/dev/null 2>&1 &
github:
    prebuilds:
        pullRequestsFromForks: true
